authors        = ["und3fined <me@und3fined.com>"]
description    = "EmmyLua a revolutionary Lua development experience"
id             = "emmylua-ls"
name           = "EmmyLua Language Server"
repository     = "https://github.com/und3fined/zed-emmylua-ls"
schema_version = 1
version        = "0.2.0"

[language_servers.emmylua]
language = "Lua"
languages = [
  "Lua",
]
name = "EmmnyLua Language Server"

[language_servers.emmylua.language_ids]
"Lua" = "lua"

[grammars.lua]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-lua"
commit = "d76023017f7485eae629cb60d406c7a1ca0f40c9"
