name: Close issues

on:
  schedule:
    - cron: "0 0 * * *"

permissions:
  issues: write

jobs:
  close-issues:
    if: github.repository == 'und3fined/zed-emmylua-ls'
    runs-on: depot-ubuntu-24.04-arm-small
    steps:
      - name: Close issue without reproduction
        uses: actions-cool/issues-helper@45d75b6cf72bf4f254be6230cb887ad002702491 # v3.6.3
        with:
          actions: "close-issues"
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: "needs reproduction"
          inactive-day: 3
